/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panda_org_http2wrapper_Http2Core */

#ifndef _Included_com_panda_org_http2wrapper_Http2Core
#define _Included_com_panda_org_http2wrapper_Http2Core
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panda_org_http2wrapper_Http2Core
 * Method:    dohttp2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_http2wrapper_Http2Core_dohttp2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
