/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panda_org_httpwrapper_HttpCore */

#ifndef _Included_com_panda_org_httpwrapper_HttpCore
#define _Included_com_panda_org_httpwrapper_HttpCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panda_org_httpwrapper_HttpCore
 * Method:    doHttp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_httpwrapper_HttpCore_doHttp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
