/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panda_org_curlwrapper_curlwrapper */

#ifndef _Included_com_panda_org_curlwrapper_curlwrapper
#define _Included_com_panda_org_curlwrapper_curlwrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panda_org_curlwrapper_curlwrapper
 * Method:    httpCurl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_curlwrapper_curlwrapper_httpCurl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
