/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panda_org_angrypandaopenssl_OpensslCore */

#ifndef _Included_com_panda_org_angrypandaopenssl_OpensslCore
#define _Included_com_panda_org_angrypandaopenssl_OpensslCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panda_org_angrypandaopenssl_OpensslCore
 * Method:    generateKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandaopenssl_OpensslCore_generateKey
  (JNIEnv *, jclass);

/*
 * Class:     com_panda_org_angrypandaopenssl_OpensslCore
 * Method:    releaseKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_panda_org_angrypandaopenssl_OpensslCore_releaseKey
  (JNIEnv *, jclass);

/*
 * Class:     com_panda_org_angrypandaopenssl_OpensslCore
 * Method:    rsaEncrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_panda_org_angrypandaopenssl_OpensslCore_rsaEncrypt
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_panda_org_angrypandaopenssl_OpensslCore
 * Method:    rsaDecrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_panda_org_angrypandaopenssl_OpensslCore_rsaDecrypt
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_panda_org_angrypandaopenssl_OpensslCore
 * Method:    getPublicKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_panda_org_angrypandaopenssl_OpensslCore_getPublicKey
  (JNIEnv *, jclass);

/*
 * Class:     com_panda_org_angrypandaopenssl_OpensslCore
 * Method:    rsaEncryptByExtPublicKey
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_panda_org_angrypandaopenssl_OpensslCore_rsaEncryptByExtPublicKey
  (JNIEnv *, jclass, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
